################## Application Settings ####################
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EUREKA-SERVER-CLUSTERED
          uri: lb://EUREKA-SERVER-CLUSTERED
          predicates:
            - Path=/, /eureka/**, /monitor
          filters:
            - name: CircuitBreaker
          args:
            name: API-GATEWAY
          metadata:
            response-timeout: 1000
            connect-timeout: 50000

        - id: SSO-AUTH-SERVER
          uri: lb://SSO-AUTH-SERVER
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
          args:
            name: SSO-AUTH-SERVER
          metadata:
            response-timeout: 1000
            connect-timeout: 50000

  web:
    resources:
      add-mappings: true