################## Application Settings ####################
server:
  port: 8091

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wlsdnjs829/config-server
          force-pull: true
          search-paths: '{application}'
    bus:
      enabled: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: busrefresh