################## Application Settings ####################
server:
  port: 8091

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wlsdnjs829/config-server
          force-pull: true
          search-paths: '{application}'
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
---
spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: local-rabbit
    port: 5672
    username: guest
    password: guest