################## Cloud-Bus Settings ####################
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest