################## Cloud-Bus Settings ####################
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

spring:
  rabbitmq:
    host: 192.168.35.85
    port: 5672
    username: guest
    password: guest